%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/wilder/Documents/Research_at_TUM/GAAF_registration.git/SPL_SupMat/Simulations/Cube/Cube_PCDs_1728pts_0.5edge_X120Y90Z45_var_v0/rotor.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/07/28 20:54:59

%% Initialize variables.
filename = 'rotor.txt';

%% Format string for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*1s%10f%9f%11f%9f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
% VarName2 = dataArray{:, 1};
% VarName3 = dataArray{:, 2};
% VarName4 = dataArray{:, 3};
% VarName5 = dataArray{:, 4};

% The following rotor follows the GAALET convention <0,3,5,6> = 1, e1e2, e1e3, e2e3.
% Thus to convert to GABLE: r_gable = r(1) + r(2)*(e1^e2) + r(3)*(e1^e3) + r(4)*(e2^e3). 
r = [dataArray{:, 1} dataArray{:, 2} dataArray{:, 3} dataArray{:, 4}];
%r_gable = r(1) + r(2)*(e1^e2) + r(3)*(e1^e3) + r(4)*(e2^e3);

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;